/**
 * Typed access to the bundled JSON content in content/.
 *
 * All four files are generated by the scripts in scripts/ (see README) and
 * bundled with the app so every core feature works fully offline.
 */
import devotionalsJson from '@/content/devotionals.json';
import guidanceTopicsJson from '@/content/guidance-topics.json';
import prayersJson from '@/content/prayers.json';
import readingPlanJson from '@/content/reading-plan.json';

// ---------- Reading plan ----------

export interface PlanPassage {
  /** Human reference, e.g. "Genesis 1–2" or "Psalm 23". */
  reference: string;
  /**
   * bible-api.com query strings, one per chapter (the API serves at most one
   * whole chapter per request), e.g. ["genesis 1", "genesis 2"].
   */
  apiQueries: string[];
  /** Which track this passage belongs to. */
  track: 'ot' | 'nt' | 'psalms' | 'proverbs';
}

export interface PlanDay {
  day: number;
  passages: PlanPassage[];
  /** One-sentence kid-friendly summary of the day's reading. */
  kidSummary: string;
}

export const readingPlan = readingPlanJson as PlanDay[];

export function getPlanDay(day: number): PlanDay {
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  return readingPlan[clamped - 1];
}

// ---------- Devotionals ----------

export interface DevotionalQuestion {
  audience: 'little' | 'older';
  question: string;
}

export interface Devotional {
  day: number;
  title: string;
  theme: string;
  scripture: { reference: string; text: string };
  /** Warm family-level reflection, multiple paragraphs joined by \n\n. */
  reflection: string;
  questions: DevotionalQuestion[];
  familyChallenge: string;
}

export const devotionals = devotionalsJson as Devotional[];

export function getDevotional(day: number): Devotional {
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  return devotionals[clamped - 1];
}

// ---------- Prayers ----------

export interface DailyPrayer {
  day: number;
  theme: string;
  title: string;
  /**
   * Prayer lines, in order. Lines containing "______" are fill-in-the-blank
   * moments where each family member adds their own word.
   */
  lines: string[];
  /** Closing line the whole family repeats together. */
  togetherLine: string;
}

export const prayers = prayersJson as DailyPrayer[];

export function getPrayer(day: number): DailyPrayer {
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  return prayers[clamped - 1];
}

// ---------- Scripture guidance ----------

export interface GuidanceVerse {
  reference: string;
  text: string;
}

export interface GuidanceTopic {
  id: string;
  name: string;
  category: string;
  /** Synonyms and natural phrases used for fuzzy matching. */
  keywords: string[];
  /** 2–3 sentence pastoral note on how these passages speak to the situation. */
  note: string;
  verses: GuidanceVerse[];
}

export const guidanceTopics = guidanceTopicsJson as GuidanceTopic[];

export function getGuidanceTopic(id: string): GuidanceTopic | undefined {
  return guidanceTopics.find((t) => t.id === id);
}

export const guidanceCategories: string[] = [...new Set(guidanceTopics.map((t) => t.category))];
