/**
 * Typed access to the bundled JSON content in content/.
 *
 * Locale-aware: Spanish overlays from *.es.json with English fallback.
 */
import devotionalsEn from '@/content/devotionals.json';
import guidanceTopicsEn from '@/content/guidance-topics.json';
import prayersEn from '@/content/prayers.json';
import readingPlanEn from '@/content/reading-plan.json';
import { getLocale, type AppLocale } from '@/i18n/index';

// Spanish bundles — generated by scripts/generate-spanish-content.js
import devotionalsEs from '@/content/devotionals.es.json';
import guidanceTopicsEs from '@/content/guidance-topics.es.json';
import prayersEs from '@/content/prayers.es.json';
import readingPlanEs from '@/content/reading-plan.es.json';

// ---------- Reading plan ----------

export interface PlanPassage {
  reference: string;
  apiQueries: string[];
  track: 'ot' | 'nt' | 'psalms' | 'proverbs';
}

export interface ParentNotes {
  trigger: string;
  little: string;
  older: string;
  teen?: string;
}

export interface PlanDay {
  day: number;
  passages: PlanPassage[];
  kidSummary: string;
  teachingPoint?: string;
  bedtimeHighlight?: string[];
  parentNotes?: ParentNotes;
}

export interface PlanDayOverlay {
  day: number;
  kidSummary?: string;
  teachingPoint?: string;
  bedtimeHighlight?: string[];
  parentNotes?: ParentNotes;
}

const readingPlanByLocale: Record<AppLocale, PlanDay[]> = {
  en: readingPlanEn as PlanDay[],
  es: mergeReadingPlan(readingPlanEn as PlanDay[], readingPlanEs as PlanDayOverlay[]),
};

function mergeReadingPlan(base: PlanDay[], overlay: PlanDayOverlay[]): PlanDay[] {
  const byDay = new Map(overlay.map((d) => [d.day, d]));
  return base.map((day) => {
    const es = byDay.get(day.day);
    if (!es) return day;
    return {
      ...day,
      kidSummary: es.kidSummary ?? day.kidSummary,
      teachingPoint: es.teachingPoint ?? day.teachingPoint,
      bedtimeHighlight: es.bedtimeHighlight ?? day.bedtimeHighlight,
      parentNotes: es.parentNotes ?? day.parentNotes,
    };
  });
}

export const readingPlan = readingPlanEn as PlanDay[];

export function getPlanDay(day: number, locale?: AppLocale): PlanDay {
  const loc = locale ?? getLocale();
  const plan = readingPlanByLocale[loc] ?? readingPlanByLocale.en;
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  return plan[clamped - 1];
}

// ---------- Devotionals ----------

export interface DevotionalQuestion {
  audience: 'little' | 'older';
  question: string;
}

export interface Devotional {
  day: number;
  title: string;
  theme: string;
  scripture: { reference: string; text: string };
  reflection: string;
  questions: DevotionalQuestion[];
  familyChallenge: string;
}

const devotionalsByLocale: Record<AppLocale, Devotional[]> = {
  en: devotionalsEn as Devotional[],
  es: devotionalsEs as Devotional[],
};

export const devotionals = devotionalsEn as Devotional[];

export function getDevotional(day: number, locale?: AppLocale): Devotional {
  const loc = locale ?? getLocale();
  const list = devotionalsByLocale[loc] ?? devotionalsByLocale.en;
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  const item = list[clamped - 1];
  const fallback = devotionalsByLocale.en[clamped - 1];
  return mergeDevotional(fallback, item, loc);
}

function mergeDevotional(en: Devotional, es: Devotional, locale: AppLocale): Devotional {
  if (locale === 'en') return en;
  return {
    day: en.day,
    title: es.title || en.title,
    theme: es.theme || en.theme,
    scripture: {
      reference: en.scripture.reference,
      text: es.scripture?.text || en.scripture.text,
    },
    reflection: es.reflection || en.reflection,
    questions: es.questions?.length ? es.questions : en.questions,
    familyChallenge: es.familyChallenge || en.familyChallenge,
  };
}

// ---------- Prayers ----------

export interface DailyPrayer {
  day: number;
  theme: string;
  title: string;
  lines: string[];
  togetherLine: string;
}

const prayersByLocale: Record<AppLocale, DailyPrayer[]> = {
  en: prayersEn as DailyPrayer[],
  es: prayersEs as DailyPrayer[],
};

export const prayers = prayersEn as DailyPrayer[];

export function getPrayer(day: number, locale?: AppLocale): DailyPrayer {
  const loc = locale ?? getLocale();
  const list = prayersByLocale[loc] ?? prayersByLocale.en;
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  const item = list[clamped - 1];
  const fallback = prayersByLocale.en[clamped - 1];
  return mergePrayer(fallback, item, loc);
}

function mergePrayer(en: DailyPrayer, es: DailyPrayer, locale: AppLocale): DailyPrayer {
  if (locale === 'en') return en;
  return {
    day: en.day,
    theme: es.theme || en.theme,
    title: es.title || en.title,
    lines: es.lines?.length ? es.lines : en.lines,
    togetherLine: es.togetherLine || en.togetherLine,
  };
}

// ---------- Scripture guidance ----------

export interface GuidanceVerse {
  reference: string;
  text: string;
}

export interface GuidanceTopic {
  id: string;
  name: string;
  category: string;
  keywords: string[];
  note: string;
  verses: GuidanceVerse[];
}

const guidanceByLocale: Record<AppLocale, GuidanceTopic[]> = {
  en: guidanceTopicsEn as GuidanceTopic[],
  es: guidanceTopicsEs as GuidanceTopic[],
};

export const guidanceTopics = guidanceTopicsEn as GuidanceTopic[];

export function getGuidanceTopics(locale?: AppLocale): GuidanceTopic[] {
  const loc = locale ?? getLocale();
  return guidanceByLocale[loc] ?? guidanceByLocale.en;
}

export function getGuidanceTopic(id: string, locale?: AppLocale): GuidanceTopic | undefined {
  const topics = getGuidanceTopics(locale);
  const topic = topics.find((t) => t.id === id);
  if (!topic) return undefined;
  if ((locale ?? getLocale()) === 'en') return topic;
  const enTopic = guidanceByLocale.en.find((t) => t.id === id);
  if (!enTopic) return topic;
  return mergeGuidanceTopic(enTopic, topic);
}

function mergeGuidanceTopic(en: GuidanceTopic, es: GuidanceTopic): GuidanceTopic {
  return {
    id: en.id,
    name: es.name || en.name,
    category: es.category || en.category,
    keywords: es.keywords?.length ? es.keywords : en.keywords,
    note: es.note || en.note,
    verses: es.verses?.length
      ? es.verses.map((v, i) => ({
          reference: v.reference || en.verses[i]?.reference || v.reference,
          text: v.text || en.verses[i]?.text || v.text,
        }))
      : en.verses,
  };
}

export function getGuidanceCategories(locale?: AppLocale): string[] {
  return [...new Set(getGuidanceTopics(locale).map((t) => t.category))];
}

/** @deprecated Use getGuidanceCategories(locale) */
export const guidanceCategories: string[] = getGuidanceCategories('en');
