/**
 * Typed access to the bundled JSON content in content/.
 *
 * All four files are generated by the scripts in scripts/ and bundled with
 * the app so every core feature works fully offline. Spanish variants live in
 * content/es/ and are populated by scripts/translate-to-spanish.js; missing
 * entries fall back to English automatically.
 */
import i18next from 'i18next';

import devotionalsJson from '@/content/devotionals.json';
import guidanceTopicsJson from '@/content/guidance-topics.json';
import prayersJson from '@/content/prayers.json';
import readingPlanJson from '@/content/reading-plan.json';

import esDevotionalsJson from '@/content/es/devotionals.json';
import esGuidanceTopicsJson from '@/content/es/guidance-topics.json';
import esPrayersJson from '@/content/es/prayers.json';
import esReadingPlanJson from '@/content/es/reading-plan.json';

function isEs(): boolean {
  return i18next.language === 'es';
}

// ---------- Reading plan ----------

export interface PlanPassage {
  reference: string;
  apiQueries: string[];
  track: 'ot' | 'nt' | 'psalms' | 'proverbs';
}

export interface PlanDay {
  day: number;
  passages: PlanPassage[];
  kidSummary: string;
}

export const readingPlan = readingPlanJson as PlanDay[];

export function getPlanDay(day: number): PlanDay {
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  const en = readingPlanJson[clamped - 1] as PlanDay;
  if (isEs()) {
    const es = (esReadingPlanJson as Partial<PlanDay>[])[clamped - 1];
    if (es?.kidSummary) return { ...en, kidSummary: es.kidSummary };
  }
  return en;
}

// ---------- Devotionals ----------

export interface DevotionalQuestion {
  audience: 'little' | 'older';
  question: string;
}

export interface Devotional {
  day: number;
  title: string;
  theme: string;
  scripture: { reference: string; text: string };
  reflection: string;
  questions: DevotionalQuestion[];
  familyChallenge: string;
}

export const devotionals = devotionalsJson as Devotional[];

export function getDevotional(day: number): Devotional {
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  if (isEs()) {
    const es = (esDevotionalsJson as Partial<Devotional>[])[clamped - 1];
    if (es?.title) return es as Devotional;
  }
  return devotionalsJson[clamped - 1] as Devotional;
}

// ---------- Prayers ----------

export interface DailyPrayer {
  day: number;
  theme: string;
  title: string;
  lines: string[];
  togetherLine: string;
}

export const prayers = prayersJson as DailyPrayer[];

export function getPrayer(day: number): DailyPrayer {
  const clamped = Math.min(365, Math.max(1, Math.round(day)));
  if (isEs()) {
    const es = (esPrayersJson as Partial<DailyPrayer>[])[clamped - 1];
    if (es?.title) return es as DailyPrayer;
  }
  return prayersJson[clamped - 1] as DailyPrayer;
}

// ---------- Scripture guidance ----------

export interface GuidanceVerse {
  reference: string;
  text: string;
}

export interface GuidanceTopic {
  id: string;
  name: string;
  category: string;
  keywords: string[];
  note: string;
  verses: GuidanceVerse[];
}

export const guidanceTopics = guidanceTopicsJson as GuidanceTopic[];

export function getGuidanceTopic(id: string): GuidanceTopic | undefined {
  const pool = isEs() && (esGuidanceTopicsJson as GuidanceTopic[]).length > 0
    ? (esGuidanceTopicsJson as GuidanceTopic[])
    : (guidanceTopicsJson as GuidanceTopic[]);
  return pool.find((t) => t.id === id);
}

export const guidanceCategories: string[] = [...new Set(guidanceTopics.map((t) => t.category))];
