/**
 * Printable / shareable weekly family sheet.
 */
import { getDevotional, getPlanDay, getPrayer } from '@/lib/content';
import { memoryVerseForDay } from '@/lib/memory-verse';
import type { WeeklyRecap } from '@/lib/weekly-recap';

export interface WeeklySheetInput {
  familyName: string;
  recap: WeeklyRecap;
  sundayNote?: string;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** HTML suitable for expo-print or browser print. */
export function buildWeeklySheetHtml(input: WeeklySheetInput): string {
  const { familyName, recap, sundayNote } = input;
  const memoryVerse = memoryVerseForDay(recap.startDay);
  const prayerTheme = getPrayer(recap.startDay).theme;

  const dayRows = recap.days
    .map((d) => {
      const plan = getPlanDay(d.day);
      const devotional = getDevotional(d.day);
      return `<tr>
        <td><strong>Day ${d.day}</strong><br/><small>${escapeHtml(d.dateLabel)}</small></td>
        <td>${escapeHtml(plan.passages.map((p) => p.reference).join(' · '))}</td>
        <td>${escapeHtml(devotional.theme)}</td>
      </tr>`;
    })
    .join('\n');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Faith & Family — Week of ${escapeHtml(recap.weekLabel)}</title>
  <style>
    body { font-family: Georgia, serif; color: #3d3428; padding: 24px; max-width: 720px; margin: 0 auto; }
    h1 { font-size: 22px; color: #8b6914; }
    h2 { font-size: 16px; color: #6b5a45; margin-top: 24px; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    td { border-bottom: 1px solid #e8dcc8; padding: 8px 4px; vertical-align: top; }
    .verse { font-style: italic; background: #faf6ef; padding: 12px; border-radius: 8px; }
    .meta { color: #7a6f5f; font-size: 13px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(familyName || 'Our Family')} — This Week in the Word</h1>
  <p class="meta">${escapeHtml(recap.weekLabel)}</p>

  <h2>Memory verse</h2>
  <div class="verse">"${escapeHtml(memoryVerse.text)}" — <em>${escapeHtml(memoryVerse.reference)}</em></div>

  <h2>Prayer theme</h2>
  <p>${escapeHtml(prayerTheme)}</p>

  <h2>Daily readings</h2>
  <table>
    <thead><tr><th>Day</th><th>Readings</th><th>Theme</th></tr></thead>
    <tbody>${dayRows}</tbody>
  </table>

  ${
    sundayNote
      ? `<h2>From church this week</h2><p>${escapeHtml(sundayNote)}</p>`
      : ''
  }

  <p class="meta" style="margin-top:32px;">Generated by Faith & Family</p>
</body>
</html>`;
}

/** Plain-text version for Share API. */
export function buildWeeklySheetText(input: WeeklySheetInput): string {
  const { familyName, recap, sundayNote } = input;
  const memoryVerse = memoryVerseForDay(recap.startDay);
  const lines: string[] = [
    `${familyName || 'Our Family'} — This Week in the Word`,
    recap.weekLabel,
    '',
    'Memory verse:',
    `"${memoryVerse.text}" — ${memoryVerse.reference}`,
    '',
    'This week:',
  ];

  for (const d of recap.days) {
    const plan = getPlanDay(d.day);
    lines.push(`Day ${d.day} (${d.dateLabel}): ${plan.passages.map((p) => p.reference).join(' · ')} — ${d.theme}`);
  }

  if (sundayNote) {
    lines.push('', 'From church:', sundayNote);
  }

  lines.push('', '— Faith & Family');
  return lines.join('\n');
}
